name: Build Artifacts

on:
  push:
    branches:
      - '*'
  watch:
    types: [started]  
    
jobs:
    
  build:

    name: Runs on Ubuntu latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
        
#       - name: Set env variables
#         run: echo '::set-env name=HAS_DEBUG_ARTIFACT::false' && echo '::set-env name=HAS_RELEASE_ARTIFACT::false'
        
      - name: Checking out repository      
        uses: actions/checkout@v2
        
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run test
        run: ./gradlew test

      # Debug APK

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Get Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Set HAS_DEBUG_ARTIFACT to true
        run: echo '::set-env name=HAS_DEBUG_ARTIFACT::true'

          
