name: Build Artifacts

on:
  push:
    branches:
      - '*'
  watch:
    types: [started]

jobs:
    
  build:

    runs-on: ubuntu-latest

    steps:
        
      - name: Set env variables
        working-directory: ./android
        run: echo '::set-env name=HAS_DEBUG_ARTIFACT::false' && echo '::set-env name=HAS_RELEASE_ARTIFACT::false'
        
      - name: Checking out repository      
        uses: actions/checkout@v2
        working-directory: ./android
        
      - name: Set Up JDK
        working-directory: ./android
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run test
        working-directory: ./android
        run: ./gradlew test

      # Debug APK

      - name: Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug
        
      - name: Get Debug APK
        working-directory: ./android
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Set HAS_DEBUG_ARTIFACT to true
        working-directory: ./android
        run: echo '::set-env name=HAS_DEBUG_ARTIFACT::true'

          
